import type { NewProduct } from "@/db/schema";

export const seedProducts: NewProduct[] = [
  {
    name: "Diamond Solitaire Ring",
    nameKu: "ئەڵماسی سۆلیتێر",
    category: "ring",
    description: "Classic solitaire diamond ring set in 21k gold with brilliant-cut center stone.",
    descriptionKu: "ئەڵماسی سۆلیتێری کلاسیک لە زێری ٢١ عەیار بە بەردی ناوەندی درەوشاوە.",
    price: "2850.00",
    priceNote: "بە پشکنین",
    pricePerGram: "95.00",
    makingFee: "25.00",
    makingFeeType: "per_gram",
    material: "gold21",
    karat: "21",
    weight: "٤٫٥ گرام",
    imageUrl: "/images/gold-diamond-ring.jpg",
    featured: true,
    inStock: true,
  },
  {
    name: "Royal Gold Ring",
    nameKu: "ئەڵقەی شاهانە",
    category: "ring",
    description: "Ornate 21k gold ring with handcrafted traditional Kurdish motifs.",
    descriptionKu: "ئەڵقەی زێری ٢١ عەیار بە نەخشی دەستکردی کوردی و نەریتی.",
    priceNote: "بە پشکنین",
    pricePerGram: "92.00",
    makingFee: "30.00",
    makingFeeType: "per_gram",
    material: "gold21",
    karat: "21",
    weight: "٦٫٢ گرام",
    imageUrl: "/images/gold-ring.jpg",
    featured: true,
    inStock: true,
  },
  {
    name: "Filigree Gold Necklace",
    nameKu: "ملوانکەی زێری نەخشی",
    category: "necklace",
    description: "Exquisite filigree gold necklace with gemstone pendant, traditional craftsmanship.",
    descriptionKu: "ملوانکەی زێری نایاب بە ئاڵتوونی بەردین و کاری دەستی نەریتی.",
    priceNote: "بە پشکنین",
    pricePerGram: "92.00",
    makingFee: "35.00",
    makingFeeType: "per_gram",
    material: "gold21",
    karat: "21",
    weight: "١٢ گرام",
    imageUrl: "/images/gold-necklace.jpg",
    featured: true,
    inStock: true,
  },
  {
    name: "Engraved Gold Bangle",
    nameKu: "دەستبەندی زێر بە نەخش",
    category: "bracelet",
    description: "Heavy 21k gold bangle bracelet with traditional engraved patterns.",
    descriptionKu: "دەستبەندی زێری قورسی ٢١ عەیار بە نەخشی نەریتی.",
    priceNote: "بە پشکنین",
    pricePerGram: "92.00",
    makingFee: "28.00",
    makingFeeType: "per_gram",
    material: "gold21",
    karat: "21",
    weight: "١٨ گرام",
    imageUrl: "/images/gold-bracelet.jpg",
    featured: true,
    inStock: true,
  },
  {
    name: "Diamond Drop Earrings",
    nameKu: "گوێوارەی ئەڵماسی شێوە دڵۆپ",
    category: "earring",
    description: "Elegant chandelier diamond and pearl earrings in 18k gold.",
    descriptionKu: "گوێوارەی شاندار بە ئەڵماس و مرواری لە زێری ١٨ عەیار.",
    priceNote: "بە پشکنین",
    pricePerGram: "80.00",
    makingFee: "40.00",
    makingFeeType: "per_gram",
    material: "gold18",
    karat: "18",
    weight: "٥٫٨ گرام",
    imageUrl: "/images/gold-earrings.jpg",
    featured: false,
    inStock: true,
  },
  {
    name: "Luxury Gold Watch",
    nameKu: "کاتژمێری زێری لوکس",
    category: "watch",
    description: "Premium gold wristwatch with diamond bezel, Swiss movement.",
    descriptionKu: "کاتژمێری زێری پلە باڵا بە چوارچێوەی ئەڵماس و میکانیزمی سویسری.",
    price: "4500.00",
    priceNote: "بە پشکنین",
    makingFee: "800.00",
    makingFeeType: "total",
    material: "gold18",
    karat: "18",
    weight: "٣٥ گرام",
    imageUrl: "/images/gold-watch.jpg",
    featured: true,
    inStock: true,
  },
  {
    name: "Bridal Gold Set",
    nameKu: "سێتی زێری بوکێنی",
    category: "set",
    description: "Complete bridal jewelry set: necklace, earrings, bracelet and ring in 21k gold.",
    descriptionKu: "سێتی تەواوی زێری بوکێنی: ملوانکە، گوێوارە، دەستبەند و ئەڵقە لە زێری ٢١ عەیار.",
    priceNote: "بە پشکنین",
    pricePerGram: "92.00",
    makingFee: "32.00",
    makingFeeType: "per_gram",
    material: "gold21",
    karat: "21",
    weight: "٤٥ گرام",
    imageUrl: "/images/gold-set.jpg",
    featured: true,
    inStock: true,
  },
];
